# Generated by Django 2.2.1 on 2019-05-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        ('user', '0001_initial'),
        ('exam', '0002_studentexam_problem_submissions'),
        ('course', '0002_auto_20190515_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student'),
        ),
        migrations.AddField(
            model_name='examproblem',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam'),
        ),
        migrations.AddField(
            model_name='examproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='exams', through='exam.StudentExam', to='user.Student'),
        ),
    ]
