version: '3'
services:
  backend:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_USER_PASSWORD=root
      - DB_NAME=oj
    ports:
      - "0.0.0.0:4000:8000"
      - "0.0.0.0:80:80"
    container_name: oj-backend
    depends_on: 
      - db

  db:
    image: daocloud.io/library/mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oj
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
