# Generated by Django 2.2.1 on 2019-05-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        ('course', '0001_initial'),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='lectures', through='lecture.LectureProblem', to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='course.CourseResource'),
        ),
    ]
