# Generated by Django 2.2.1 on 2019-05-15 15:49

from django.db import migrations, models
import django.db.models.deletion
import submission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        ('lecture', '0002_auto_20190515_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('runtime', models.BigIntegerField()),
                ('memory', models.BigIntegerField()),
                ('IP', models.CharField(max_length=20)),
                ('language', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSubmissionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_info', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Case')),
                ('case_status', models.ForeignKey(default=submission.models.CaseStatus.default, on_delete=django.db.models.deletion.SET_DEFAULT, to='submission.CaseStatus')),
                ('problem_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.ProblemSubmission')),
            ],
        ),
        migrations.AddField(
            model_name='problemsubmission',
            name='cases',
            field=models.ManyToManyField(blank=True, related_name='problem_submissions', through='submission.ProblemSubmissionCase', to='problem.Case'),
        ),
        migrations.AddField(
            model_name='problemsubmission',
            name='lectures',
            field=models.ManyToManyField(blank=True, related_name='problem_submissions', to='lecture.Lecture'),
        ),
        migrations.AddField(
            model_name='problemsubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
