# Generated by Django 2.2.1 on 2019-05-29 06:57

from django.db import migrations, models
import django.db.models.deletion
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_problemsubmission_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsubmission',
            name='submission_status',
            field=models.ForeignKey(default=submission.models.CaseStatus.default, on_delete=django.db.models.deletion.SET_DEFAULT, to='submission.CaseStatus'),
        ),
    ]
