# Generated by Django 2.2.1 on 2019-06-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20190515_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='lab_submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment', to='lab.LabSubmission'),
        ),
    ]
