# Generated by Django 2.2.1 on 2019-06-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20190603_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='problem.Problem'),
        ),
    ]
