# Generated by Django 2.2.1 on 2019-06-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20190604_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labproblem',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='lab.Lab'),
        ),
        migrations.AlterField(
            model_name='labproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
