# Generated by Django 2.2.1 on 2019-05-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0002_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Role',
        ),
    ]
