# Generated by Django 2.2.1 on 2019-05-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0003_auto_20190525_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='group_ptr',
        ),
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(to='user.Permission'),
        ),
    ]
