# Generated by Django 2.2.1 on 2019-05-25 18:07

from django.db import migrations
from user.models import Permission


def op(apps, schema_editor):
    Permission.objects.create(name="教师管理")
    Permission.objects.create(name="学生管理")
    Permission.objects.create(name="课程系列管理")
    Permission.objects.create(name="课程管理")
    Permission.objects.create(name="考试管理")
    Permission.objects.create(name="考试密码管理")
    Permission.objects.create(name="消息管理")
    Permission.objects.create(name="编程题目管理")
    Permission.objects.create(name="标签管理")
    Permission.objects.create(name="报告题目管理")
    Permission.objects.create(name="课程资源管理")
    Permission.objects.create(name="实验题目管理")
    Permission.objects.create(name="权限管理")
    Permission.objects.create(name="角色管理")


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190526_0156'),
    ]

    operations = [
        migrations.RunPython(op)
    ]
